name: Get Screenshots
on: workflow_dispatch # 允许你手动点击按钮开始

jobs:
  run-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许机器人把图片传回你的仓库
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp
      - name: Run Script
        env: 
          MY_COOKIES: ${{ secrets.YT_COOKIES }} # 读取 Secret
        run: |
          echo "$MY_COOKIES" > cookies.txt # 还原为文件
          python capture.py
          rm cookies.txt # 运行完删除，保护隐私
          
      - name: Save to Repo
        run: |
          git config --local user.email "javainstalling@gmail.com"
          git config --local user.name "microHX"
          git add screenshots/
          git commit -m "Add screenshots" || exit 0
          git push
          
      - name: Upload Screenshots as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-screenshots # 给产物起个名字
          path: screenshots/     # 告诉 GitHub 备份这个文件夹
